qa:
  users:
    valid_user: "standard_user"
    invalid_user: "invalid_user"
    locked_user: "locked_out_user"
  reports_path: "target/reports/"

  passwords:
    valid_user: "secret_sauce"
    invalid_user: "secret_sauce"
    locked_user: "secret_sauce"

preprod:
  users:
    valid_user: "standard_user"
    invalid_user: "invalid_user"
    locked_user: "locked_out_user"
    password: "secret_sauce"
  reports_path: "target/reports/"

  passwords:
    valid_user: "secret_sauce"
    invalid_user: "secret_sauce"
    locked_user: "secret_sauce"